# Connection settings
network.host: 0.0.0.0
transport.host: localhost
transport.tcp.port: 9300

# Memory settings
bootstrap.memory_lock: true

# Cluster settings
cluster.name: es-cluster
cluster.initial_master_nodes: es01,es02

### x-pack functions
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: true
xpack.watcher.enabled: false
